-- Dieser Teil wurde nach cl_gameplay.lua verschoben, um alles Gameplay-relevante an einem Ort zu haben.
-- cl_nui.lua dient nur noch als Platzhalter für eventuelle zukünftige NUI-spezifische Client-Logik.
